### ISSUE TITLE
Ridiculous "This exists for static type-checking purposes only" error message

### ISSUE THREAD

**Issue by zatherz** [WojciechNagorski/ExtendedXmlSerializer#266] opened 2019-10-12 08:33 UTC
Version 2.1.23.
```
System.InvalidOperationException: This exists for static type-checking purposes only.
  at ExtendedXmlSerializer.ContentModel.SerializerMarker.ExtendedXmlSerializer.ContentModel.IWriter<System.Object>.Write (ExtendedXmlSerializer.ContentModel.Format.IFormatWriter writer, System.Object instance) [0x00000] in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\SerializerAdapter.cs:77 
  at ExtendedXmlSerializer.Write`1[T].Execute (ExtendedXmlSerializer.ContentModel.Format.Writing`1[T] parameter) [0x00000] in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Write.cs:43 
  at ExtendedXmlSerializer.Serializer`2[TRead,TWrite].Serialize (TWrite writer, System.Object instance) [0x00000] in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Serializer.cs:41 
  at ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Serialize (System.Xml.XmlWriter writer, System.Object instance) [0x00000] in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\ExtendedXmlSerializer.cs:40 
```

Code that causes the issue:
```cs
var m = new XMLModMetadata();
m.Author = "me";
m.Name = "test";
m.Description = "desc";
var ms = new MemoryStream();
using (var xw = XmlWriter.Create(ms)) {
    new ConfigurationContainer().Create().Serialize(xw, m);
    xw.Flush();
}
```

**Comment by Mike-EEE** [comment] 2019-10-12 11:13
Hey @zatherz thanks for writing in.  I agree... this error is **_SO_** ridiculous that I can't even reproduce it. 😆  I've created a passing test with your provided code here:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/8fd479a1045cc9191ff3480024913f1fd0d6fbdc/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue266Tests.cs#L10-L21

Perhaps this might be a caching issue?  Try deleting your `C:\Users\<user>\.nuget\ExtendedXmlSerializer` folder and do a rebuild of your solution. 🤞

**Comment by Mike-EEE** [comment] 2019-10-23 07:27
Since we have not heard a reply, closing this issue for now.  Please feel free to comment if any questions remain.

**Closed by Mike-EEE** 2019-10-23 07:27 UTC
Labels: sample code
